### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by Thundermaker300**
Moved from https://github.com/Exiled-Team/EXILED/pull/1375

### CODE REVIEW

**Comment by Michal78900** [comment]
`or not` is redundant

**Comment by Thundermaker300** [comment]
How is it supposed to be? "Whether or not [info]" or "Whether [info] or not"?

**Comment by iopietro** [comment]
I do like "Whether [info] or not".

**Comment by Thundermaker300** [comment]
sadge

**Comment by iopietro** [comment]
So, what do we do?

**Comment by louis1706** [comment]
> I do like "Whether [info] or not".

i suggest to make "Whether or not [info] or not".
:trollface:

**Comment by Thundermaker300** [comment]
funny man

**Comment by Thundermaker300** [comment]
Resigned

**Pull request merged**
